# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: 5cc16bee7effc371ac183edf67df669b00e1b016c378a874785d56647f6dd5c1b52146d05002b38bd7525efb72439b15169b15dc7f43a3571bfcb8e2cbbdf1c5
  s3_ul_bucket: <%= ENV["S3_UL_BUCKET"] %>
  s3_ul_success_base: <%= ENV["S3_UL_SUCCESS_BASE"] %>
  s3_ul_access_key: <%= ENV["S3_UL_ACCESS_KEY"] %>
  s3_ul_access_secret: <%= ENV["S3_UL_ACCESS_SECRET"] %>

test:
  secret_key_base: 6bc11ade99a3d1d6f589d3f62bc42990e21420fbcc86ccacb3c44cfc23036dcad6c874f9343b1733d2568a53334eb903d4693aaa6bf9c0535e7ba614c28d70f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_ul_bucket: <%= ENV["S3_UL_BUCKET"] %>
  s3_ul_success_base: <%= ENV["S3_UL_SUCCESS_BASE"] %>
  s3_ul_access_key: <%= ENV["S3_UL_ACCESS_KEY"] %>
  s3_ul_access_secret: <%= ENV["S3_UL_ACCESS_SECRET"] %>